# Generated by Django 2.2.3 on 2019-08-27 19:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('category_id', models.IntegerField(default=0)),
                ('tag', models.CharField(choices=[('P_M', 'Parrot Movement'), ('P_V', 'Parrot Voice'), ('P_A', 'Parrot Auto')], max_length=4)),
                ('arg', models.IntegerField(unique=True)),
                ('priority', models.IntegerField(default=10)),
                ('voice_file', models.FileField(blank=True, upload_to='')),
                ('perform_time', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnoseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField(default=False)),
                ('finish_time', models.BigIntegerField(default=0)),
                ('played_game', models.BooleanField(default=True)),
                ('played_toycar', models.BooleanField(default=True)),
                ('expertsystem_judgement', models.CharField(choices=[('AUTISTIC_HP', 'اتیسم به احتمال قوی'), ('AUTISTIC_LP', 'اتیسم به احتمال  ضعیف'), ('NOT_AUTISTIC', 'عدم تشخیص اتیسم'), ('NA', 'NA')], default='NA', max_length=16)),
                ('paused', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_duration_minutes', models.SmallIntegerField(default=1)),
                ('wheel_duration_minutes', models.SmallIntegerField(default=1)),
                ('parrot_duration_minutes', models.SmallIntegerField(default=1)),
                ('diagnose_duration_minutes', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator])),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10)),
                ('medical_info', models.CharField(choices=[('ADHD', 'ADHD'), ('normal', 'نرمال'), ('autism', 'اتیسم'), ('NA', 'تعیین نشده')], default='NA', max_length=10)),
                ('person_id', models.CharField(max_length=10, unique=True, validators=[website.models.is_valid_iran_code])),
                ('login_status', models.BooleanField(default=False)),
                ('last_activity', models.BigIntegerField(default=website.models.getTime)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField()),
                ('duration', models.IntegerField()),
                ('name', models.CharField(choices=[('NS', 'not started'), ('G', 'game'), ('W', 'Wheel'), ('P', 'parrot'), ('DIAGNOSE', 'diagnose'), ('DONE', 'done')], default='NS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ToyCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField()),
                ('ac_x', models.BigIntegerField()),
                ('ac_y', models.BigIntegerField()),
                ('ac_z', models.BigIntegerField()),
                ('encode1', models.BigIntegerField()),
                ('encode2', models.BigIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DiagnoseSession')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosesession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Patient'),
        ),
        migrations.AddField(
            model_name='diagnosesession',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Stage'),
        ),
    ]
