# Generated by Django 2.0.3 on 2019-09-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(choices=[('GAME_STAGE', 'game'), ('WHEEL_STAGE', 'Wheel'), ('PARROT_STAGE', 'parrot'), ('DONE', 'done')], default='GAME_STAGE', max_length=2),
        ),
    ]
