# Generated by Django 2.0.3 on 2019-09-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190904_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteproperty',
            old_name='control_start_manual',
            new_name='prestart_help',
        ),
    ]
