# Generated by Django 2.0.3 on 2019-09-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190904_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproperty',
            name='prestart_help',
            field=models.CharField(default='Please modify this in your admin settings', max_length=8192),
        ),
    ]
