# Generated by Django 2.0.3 on 2019-09-06 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190906_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrontEnd_Config',
            new_name='FrontConfig',
        ),
    ]
