# Generated by Django 2.0.3 on 2019-09-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190906_2244'),
        ('website', '0002_auto_20190902_1636'),
    ]

    operations = [
    ]
