# Generated by Django 2.0.3 on 2019-10-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_merge_20190929_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration',
            name='diagnose_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='duration',
            name='game_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='duration',
            name='parrot_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='duration',
            name='wheel_duration_minutes',
        ),
        migrations.AddField(
            model_name='duration',
            name='game_duration_seconds',
            field=models.SmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='duration',
            name='parrot_duration_seconds',
            field=models.SmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='duration',
            name='wheel_duration_seconds',
            field=models.SmallIntegerField(default=60),
        ),
    ]
