# defaults
# integer field (minutes)
DEFAULT_GAME_DURATION = 1
DEFAULT_WHEEL_DURATION = 1
DEFAULT_PARROT_DURATION = 1
DEFAULT_DIAGNOSE_DURATION= 1

GAME_STAGE = "GAME_STAGE"
WHEEL_STAGE = "WHEEL_STAGE"
PARROT_STAGE = "PARROT_STAGE"
DONE_STAGE = "DONE"


from website.ros import ROS
ros = ROS()